CREATE TABLE loan_request
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenure       INT                                     NOT NULL,
    amount       DOUBLE PRECISION                        NOT NULL,
    status       VARCHAR(255),
    request_date date,
    CONSTRAINT pk_loan_request PRIMARY KEY (id)
);


CREATE TABLE bank_account
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_number      VARCHAR(255),
    account_holder_name VARCHAR(255),
    balance             DOUBLE PRECISION                        NOT NULL,
    account_type        VARCHAR(255),
    created_at          TIMESTAMP,
    CONSTRAINT pk_bank_account PRIMARY KEY (id)
);

CREATE TABLE bank_account_loan_requests
(
    bank_account_id  BIGINT NOT NULL,
    loan_requests_id BIGINT NOT NULL
);

ALTER TABLE bank_account
    ADD CONSTRAINT uc_bank_account_accountnumber UNIQUE (account_number);

ALTER TABLE bank_account_loan_requests
    ADD CONSTRAINT uc_bank_account_loan_requests_loanrequests UNIQUE (loan_requests_id);

ALTER TABLE bank_account_loan_requests
    ADD CONSTRAINT fk_banaccloareq_on_bank_account FOREIGN KEY (bank_account_id) REFERENCES bank_account (id);

ALTER TABLE bank_account_loan_requests
    ADD CONSTRAINT fk_banaccloareq_on_loan_request FOREIGN KEY (loan_requests_id) REFERENCES loan_request (id);